; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=ECM Config
AppVersion=1.1.1
DefaultDirName={pf}\ECMConfig
OutputDir=.
OutputBaseFilename=ECMConfigSetup
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\*"; DestDir: "{app}"
